### ISSUE TITLE
Error in Evaluating own system. 

### ISSUE THREAD

**Issue by november07** [evanmiltenburg/MeasureDiversity#2]
Hi, I am trying to evaluate my own system. 
I have followed the README guidelines, but have reached an error as below after running 
analyze_your_system.py's run_all function. The error looks to be in methods.py, 
`   
 189             ttr = float(len(types))/n
 190             ttrs.append(ttr)
--> 191     final_ttr = float(sum(ttrs))/len(ttrs)
 192     return final_ttr
 193

ZeroDivisionError: float division by zero
`

The input is a json file which looks like below,
` {'caption': 'a woman and a cat on a man', 'image_id': 353136},
 {'caption': 'the tower of a tall tower during the day', 'image_id': 83915},
 {'caption': 'a clock tower on top of a building that has a tree in front',
  'image_id': 129159},
 {'caption': 'a tall clock tower with a sky background', 'image_id': 529636},
 {'caption': 'a clock tower is in the middle of a park', 'image_id': 457691},
 {'caption': 'a little girl is sitting on a bed with a white teddy bear',
  'image_id': 14941},
 {'caption': 'a clock tower in a dark cloudy sky', 'image_id': 371999},
 {'caption': 'there is a photo of teddy bears', 'image_id': 2240},
 {'caption': 'a clock is sitting on a brick tower', 'image_id': 3084},
 {'caption': 'a clock on a building as a man stands in front of a building',
  'image_id': 142592},
 {'caption': 'a clock on a building with a sky background',
  'image_id': 577821},
 {'caption': 'a brick house with a church in the front', 'image_id': 28377},
 {'caption': 'a clock that looks like a tower and a clock',
  'image_id': 239448},
 {'caption': 'a vase with a flower on top of it', 'image_id': 558524},
 {'caption': 'a vase with flowers near a sink and other coming out of the bedroom',
  'image_id': 550426},
`
What could have gone wrong ? Since, the json file I prepared, is the same formate as the System json files. 

Thanks

**Comment by evanmiltenburg** [comment]
I'm trying to see what's wrong, but as a first thought: did you include the square brackets in the file with the captions? I.e. is it a JSON list? Because the part that you pasted doesn't include them.

Example from a different system:
```
[{"caption":"a man riding a really bicycle on a dirt road","image_id":391895},{"caption":"a woman standing in front of a piece of cake","image_id":522418},{"caption":"a man holds up a small child while standing near a large cow","image_id":184613}, ...]
```

**Comment by evanmiltenburg** [comment]
Ok, I've replicated the issue. At least with a smaller JSON file:

```
[{"caption": "a woman and a cat on a man", "image_id": 353136}, {"caption": "the tower of a tall tower during the day", "image_id": 83915}, {"caption": "a clock tower on top of a building that has a tree in front", "image_id": 129159}, {"caption": "a tall clock tower with a sky background", "image_id": 529636}, {"caption": "a clock tower is in the middle of a park", "image_id": 457691}, {"caption": "a little girl is sitting on a bed with a white teddy bear", "image_id": 14941}, {"caption": "a clock tower in a dark cloudy sky", "image_id": 371999}, {"caption": "there is a photo of teddy bears", "image_id": 2240}, {"caption": "a clock is sitting on a brick tower", "image_id": 3084}, {"caption": "a clock on a building as a man stands in front of a building", "image_id": 142592}, {"caption": "a clock on a building with a sky background", "image_id": 577821}, {"caption": "a brick house with a church in the front", "image_id": 28377}, {"caption": "a clock that looks like a tower and a clock", "image_id": 239448}, {"caption": "a vase with a flower on top of it", "image_id": 558524}, {"caption": "a vase with flowers near a sink and other coming out of the bedroom", "image_id": 550426}]
```

Now trying to find the source of the issue.

**Comment by evanmiltenburg** [comment]
Ok, hypothesis now: you have fewer than 1000 tokens in the data file. I've updated `methods.py`, can you try if this resolves the issue?

**Comment by november07** [comment]
Hi, yes, the number of tokens seemed to have been the issue. I am guessing the measure was originally intended to be used after a fully trained model. 

thank you

**Comment by evanmiltenburg** [comment]
Yes, the measures defined here are corpus-level metrics because diversity is a corpus-level property. (You cannot measure whether an individual sentence is diverse.)

Some properties may be useful to check at sentence level, though. E.g. whether it’s a novel sentence or not. But that’s not what this code is written for, so it might be easier to write your own script, if that’s what you want to do.
